# Generated by Django 6.0.4 on 2026-05-05 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер заказа')),
                ('order_type', models.CharField(choices=[('single', 'Единичный'), ('multiple', 'Множественный')], max_length=10, verbose_name='Тип заказа')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование заказа')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='orders/documents/', verbose_name='Документ')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'Обрабатывается'), ('assembling', 'Собирается'), ('delivering', 'Доставляется'), ('ready', 'Готов')], default='created', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('ready_date', models.DateField(blank=True, null=True, verbose_name='Дата готовности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
